#!/usr/bin/env python3

#This is lab1.py

currentyear = input('Current Year: ')

birthyear = input('Year you were born: ')

age = int(currentyear) - int(birthyear)

print(' You are ' + str(age) + ' years old!')
